# My Nord Light
[colors]
foreground = "#2E3440"
background = "#ECEFF4"
cursor_bg = "#4C566A"
cursor_fg = "#E5E9F0"
selection_bg = "#E5E9F0"
selection_fg = "#434C5E"

ansi = [
  "#2E3440",
  "#BF616A",
  "#A3BE8C",
  "#EBCB8B",
  "#5E81AC",
  "#B48EAD",
  "#88C0D0",
  "#D8DEE9",
]
brights = [
  "#4C566A",
  "#D08770",
  "#A3BE8C",
  "#EBCB8B",
  "#81A1C1",
  "#B48EAD",
  "#8FBCBB",
  "#ECEFF4",
]
